schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EC2EnvironmentInput"
  types:
    EC2EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        owner:
          type: string
          description: "Owner"
          default: Egor